name: Release

on:
  push:
    tags: ["*"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: release

    # Mandatory permission for trusted publishing to PyPi
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v6

      - name: Install uv and python 3.11
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          python-version: "3.11"

      - name: Build a binary wheel and a source tarball
        run: uv build

      - name: Store the distribution packages
        uses: actions/upload-artifact@v5
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
